name: Expo Build
on:
  push:
    branches:
      - main
jobs:
  build_web:
    name: Build Web Expo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: yarn
      - run: expo build:web

